name: Verify Pull Request

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Verify Environment Scripts
      run: |
        python -m py_compile scripts/*.py
